import mongoose from 'mongoose';

const crisisOptionSchema = new mongoose.Schema({
  label: { type: String, required: true },
  description: { type: String },
  effects: [{
    type: { type: String, enum: ['reputation', 'stability', 'resource', 'currency', 'military', 'custom'] },
    target: { type: String },  // Nation name, resource name, etc.
    value: { type: Number },
    description: { type: String },
  }],
  votes: [{
    nationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Nation' },
    nationName: { type: String },
    votedBy: { type: String },  // Discord user ID
    votedAt: { type: Date, default: Date.now },
  }],
});

const crisisSchema = new mongoose.Schema({
  // Guild (server) this crisis belongs to
  guildId: { type: String, required: true, index: true },
  
  // Basic info
  name: { type: String, required: true },
  description: { type: String, required: true },
  
  // Crisis category
  category: { 
    type: String, 
    enum: ['political', 'military', 'economic', 'humanitarian', 'environmental', 'diplomatic', 'other'],
    default: 'other'
  },
  
  // Severity level
  severity: {
    type: String,
    enum: ['minor', 'moderate', 'major', 'critical', 'catastrophic'],
    default: 'moderate',
  },
  
  // Status
  status: {
    type: String,
    enum: ['pending', 'active', 'voting', 'resolved', 'failed', 'expired'],
    default: 'active',
  },
  
  // Which nations are involved/affected
  affectedNations: [{ type: String }],  // Nation names
  
  // Response options for voting
  options: [crisisOptionSchema],
  
  // Resolution
  resolution: {
    selectedOption: { type: Number },  // Index of chosen option
    summary: { type: String },
    resolvedAt: { type: Date },
    resolvedBy: { type: String },  // 'vote', 'gm', 'expired'
  },
  
  // Timing
  startTurn: { type: Number, required: true },
  startYear: { type: Number, required: true },
  expiresInTurns: { type: Number, default: 3 },  // Auto-resolve after this many turns
  
  // Who created this crisis
  createdBy: { type: String },  // 'system' or Discord user ID
  isAutoGenerated: { type: Boolean, default: false },
  
  // Metadata
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
});

crisisSchema.index({ guildId: 1, status: 1 });
crisisSchema.index({ guildId: 1, createdAt: -1 });

crisisSchema.pre('save', function(next) {
  this.updatedAt = new Date();
  next();
});

const Crisis = mongoose.model('Crisis', crisisSchema);

export default Crisis;
