import mongoose from 'mongoose';

const historyEntrySchema = new mongoose.Schema({
  // Guild (server) this entry belongs to
  guildId: { type: String, required: true, index: true },
  
  // Game context
  turn: { type: Number, required: true },
  year: { type: Number, required: true },
  
  // Entry details
  title: { type: String, required: true },
  description: { type: String, required: true },
  
  // Category for filtering
  category: { 
    type: String, 
    enum: ['war', 'diplomacy', 'economy', 'political', 'military', 'disaster', 'discovery', 'custom'], 
    default: 'custom' 
  },
  
  // Related entities
  nations: [{ type: String }],  // Nation names involved
  
  // Who created this entry (null for system-generated)
  createdBy: { type: String, default: null },  // Discord user ID
  isAutoGenerated: { type: Boolean, default: false },
  
  // Metadata
  createdAt: { type: Date, default: Date.now },
});

historyEntrySchema.index({ guildId: 1, turn: -1 });
historyEntrySchema.index({ guildId: 1, year: -1 });
historyEntrySchema.index({ guildId: 1, category: 1 });
historyEntrySchema.index({ guildId: 1, nations: 1 });

const HistoryEntry = mongoose.model('HistoryEntry', historyEntrySchema);

/**
 * Create a history entry
 */
export async function createHistoryEntry(data) {
  return await HistoryEntry.create(data);
}

/**
 * Get history entries for a guild
 */
export async function getHistory(guildId, options = {}) {
  const { limit = 50, category = null, nation = null, fromTurn = null, toTurn = null } = options;
  
  const query = { guildId };
  
  if (category) query.category = category;
  if (nation) query.nations = nation;
  if (fromTurn !== null) query.turn = { ...query.turn, $gte: fromTurn };
  if (toTurn !== null) query.turn = { ...query.turn, $lte: toTurn };
  
  return await HistoryEntry.find(query)
    .sort({ turn: -1, createdAt: -1 })
    .limit(limit);
}

/**
 * Get history for a specific nation
 */
export async function getNationHistory(guildId, nationName, limit = 50) {
  return await HistoryEntry.find({ 
    guildId, 
    nations: nationName 
  })
    .sort({ turn: -1, createdAt: -1 })
    .limit(limit);
}

export default HistoryEntry;
